[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../terraform/iii-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[engine_gateway]
engine_gateway_vm ansible_host=98.84.46.0

[inference_worker]
inference_worker_vm ansible_host=10.0.2.209 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i ../terraform/iii-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@98.84.46.0"'

[caller_worker]
caller_worker_vm ansible_host=10.0.2.156 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i ../terraform/iii-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@98.84.46.0"'

